language: java
jdk:
- openjdk8
script: mvn clean install
deploy:
  provider: lambda
  function_name: MethodHandlerLambda
  region: eu-central-1
  role: arn:aws:iam::003829237552:role/lambda_basic_execution
  runtime: java8
  handler_name: de.developerpat.handler.LambdaMethodHandler::handleRequest
  access_key_id:
    secure: Zq0Jrf/Z92r54AxWOIyv8S1+UCHAMHLKZq0QyfdiDGce5AlMDMVxOF3sHGcFj82E8M1sRw08MIZlIxBWJPTJvg6yWBla+7je+aYeM8KfdY/ATE1tDIZz1ztuMLrEbGvX2zhrnj7KPZvK1T6Ydp7NH6njIBwpMMNTlq+SWp+va9isgO57XTdriCKAoFxNEOrG9p4MWfnHBkg0WAMgcSu5+y48i3XD2aXfw66fFQatGbptTRgspEoZEOC2Rz03/vHpsrhCmN+0N9eFYqpbcgIao/jKtgNW0Whn1p15hpSrWYkKlM4omLH8clHnAB7fSfohxoyHpAvrf6FLFDNzvQ8P6XH4YkGJSdDyX14Pf6Y/N3Y0bxmjpu2icbl3TdLHfKEi6xSXGI3/OhLtPGyOlhy1fIpT2DhyOGDMvY9/do1O5VUBsh1OoLX5n6OiOAVlMlAUtYUx1OGIe4H7zF0yQS/sUr2TBaDm2tE0kAoV2MegbzZw/1h8IPJEz21hIK3nP5jXrW7IJGdSSXjngM2P8lwyyyMz9moEZJI7o0xGABbug2jOMfha5fNuyFGBbv6Vf/Wfrf3vhSf+yzelAOKoV0ZJTDdDfmlAABnWN6tKhpwnnF109KAJmf9CU9iOznj+L+b9KChF7SxG7ZOrT53OIPzO0OW7nchOk6L6rVwNuuM1TVs=
  secret_access_key:
    secure: pvj1A/aaOETX/XEd1/W5JpU3roFq7ZOWE/xTZlxvNMaDlnu+wM8Z0k+uuMudaSF71GSB7rua14tLIGF50CV2lnKPXZoVH4dDT6dZDmDIzIkO6oJdWQOsk6PVKqjbopmXYZmmZFPtTjvJF5lhdAtg6hzbfIgalzwsZlslNDTfAncvOJV03a9fTagJ0Qwmdhmc6xsqvBK/1w7a5G4+/MxJstdX/oSfng2vHOrj/EtlV2eiDUGDmnaEGdgrDM5mP0Fx+Lzj/wViZWHePL0RnGV92+gVF9WBOH2I1fy3khwehVYSvU6d4yRlC3yA6H2aH9ShrInMhfN3hn9nol58jb/dP2fRXGJV46RVkfiEanPF0FOzZTbexMgBCWODNG+KCHIQPs+FVhojNK3MfadXneff9wY03GL1/iTKIYhlgKrsHaG5CsWiMYrTSjbEA9JWVMcMGC+YgMgbObGiLmLUzZO6szQ3Kq85MbOoo7JJfSxVFl9bf9dZbRO8OCsCjgkhYeJj3HJxqi/RfrFG84EQWuHYwWaLydilf9UETVR0Nxiqc+zIeSL1lMpNFGPzhRbviWkRiwsFhMN974Lja4BuQ1F7FVDYaoe6RdUUAK5znmRfkWNU3TfqGMXWucxsOdIP/a7ZN89IElZicifH2Zg2pf2D8nexnFaM6B/lSL/h0+Nq/FI=
