language: java
jdk:
- openjdk8
script: mvn clean install
deploy:
  provider: lambda
  function_name: MethodHandlerLambda
  region: eu-central-1
  role: arn:aws:iam::003829237552:role/lambda_basic_execution
  runtime: java8
  handler_name: 'de.developerpat.handler.LambdaMethodHandler::handleRequest'
  secret_access_key:
    secure: R1x7AA4yT2aQqL9k9qPthQ3hJloWLQru/6zzQVtLpcJSPlzTsILKGWyr5zwotNdwTurrI4PSctXikglt1Iro4TmHNneevKd7cy9782XNoO1iByR2ixt/bfgzDIsr/ws2t4iUPUPop6WBGEyeUHjztovzDYBwzjc5thaU9GfxN3z+1knO+y/H2fu4V+WYc5l1Hri0DIjrWmlwRC4uoqya0IQ4KI8uX3/NgZ7fuT/GdTWhy+cO96kxwK/7UexDpG9aZZ9jd4MMuv44R/l8n5c11t+ZxKHNtaEx5dWNfUoqH2vXe0mQIjVw7Bt/tvg8HNJrIqPv8tqr2aaGIspnCwwy01F6dhDs7Pu7JKHDvMe8Y70RQF/6H6z+u+nRlizeY3hZSGOWH/M89KKc332rm0GO2DEEqqRDYK9UiYLWAmtrKEBJNG2Q3Wg8bFSq69Gh1j6lQiw1Yfqe74R4oH+Ike8EgZ0kxbT9WDLxJswm9tA8aDyqyeEChUN58g/0nt8x+t8pKBnweDb9p/bAbZOHtDCv3r4FZsBIhwN69MB56d6mVoMFm4gvuTH1K1MTDnfshi+DW8p1WkUEf7qgF3Ceir03lNB9V0Ls/oH23iJdY6B+6W7kxUGZqyAXOJ0lc10niVR0ZbLOfFv+9yKqR6lclSBS/TZVZ9VszfVhFQijjMRXAVg=
  access_key_id:
    secure: FWFwaR5lLOp3Om4AhymO1OFxOOi8QL+2jWKjLNzZMCUAfkaVuokYRtHLUix9a2/WkUzecJ5/uXODbd3Nl2NXgdTSQh4LBtm16I/YeZntjLRrlGefUOnMW/gZm5X4L4tib9atwZ3x1nYi5JUq4O2yXaApXxfG5wZKDcseILMvTp03PKHMMICzGdKrsNPIAHFMOYf+aFXWwzPqKu/leZc7fEU0mrwzKC3Zoqh3v+/C/x+dz6gKUi5vo8TG3zveLkneCeIPFRmqWY34AQ/RY8LnxBNX6XidvSdF5ML5VRwiko5rijsRAhFuEOc1jHMIQ3y3Evd6pv+w2B2LqmUQV7zrVbcTcf/IJoTi+pwlwBC/6w+HfqJXmFtT+KQ8/z0ARt+UZj+WLAJrUoMjgIPGwwzR110E0ci/Is42QtKLiWr8Rec/6CaI/e9RmjF6+OMEMurHMhwuKnjqi3wFaSPxFKEPIVNCC/0GQHijbun5QzwMCJPA5tX2iKhJIuQCxFCfrA/dKn7kMi0k42PEYFBpMkLHbvjnUu1kFtM/v2y82NY3JqFwIXRjtSBT0LDh0HLx+EfvEcN/cjYJmxvpe3AIQoMrUoGvowJCFv3Ww/e7H0LzYlFtyusEGsP50VFDjw94hszRz4jtiIK6c08PSkjz+0XL8V/ikAhX7DS8Z99XMvtfeME=
